### ISSUE TITLE
What is the dependency of the code?

### ISSUE THREAD

**Issue by hmishfaq** [FlorenceFeng/ENIAC#1]
In the Readme under  it says, https://github.com/FlorenceFeng/ENIAC/tree/master/code/DeepRL "install pytorch, tensorflow, opencv-python, tensorboardx, gym" but it also has requirement.txt file. Is the code dependent on the exact versions of the modules mentioned in requirements.txt?

**Comment by FlorenceFeng** [comment]
Thanks for the question. Since our code directly follows one version of [Zhang 2018](https://github.com/ShangtongZhang/DeepRL), the requirements are therefore inherited. But I assume it is not restricted to the exact versions of the modules. In my current executable, I have 

mujoco-py==1.50.1.68
torch==1.7.1
gym==0.15.4
tensorflow==1.12.0
git+git://github.com/deepmind/dm_control.git@1038345fa347165b7e29fa677824b2e9ee87762f
git+https://github.com/ShangtongZhang/dm_control2gym.git@scalar_fix
torchvision==0.2.1
atari-py==0.1.7
opencv-python==4.0.0.21
tensorboardX==1.4
scikit-image==0.14.2
tqdm==4.56.0
pandas==1.1.5
pathlib==1.0.1
seaborn==0.9.0
roboschool==1.0.48

The readme under https://github.com/FlorenceFeng/ENIAC/tree/master/code/DeepRL is an old version. I will delete it later. Please follow the readme under https://github.com/FlorenceFeng/ENIAC. Sorry for the confusion.
